stages:
  - test

test:
  stage: test
  script:
    - ls
    # - docker rm $(docker stop $(docker ps -a -q -f ancestor=deploy-docker:ban-thuoc))
    # - docker rmi deploy-docker:ban-thuoc
    - docker build -t deploy-docker:ban-thuoc .
    - docker run -d --net tulip-net  -p 3001:3001 deploy-docker:ban-thuoc
    - docker ps -a
  only:
    - main
